<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddingFotoColumn extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->addColumn('cultivo','foto','string');
    }

    public function down()
    {
      $this->removeColumn('cultivo','foto');
    }
}